### ISSUE TITLE
[UI] Search bar goes out of nav

### ISSUE THREAD

**Issue by Luna-devv** [audn/css-app-frontend#12]
# Issue
The search bar goes out of the navbar component.
![image](https://user-images.githubusercontent.com/71079641/210564851-65016430-fe00-4f09-b3a9-82cae0a3ddee.png)

# Platform
Windows 11; Firefox

**Comment by audn** [comment]
possible fix: bookmark discordlist before top.gg in your bookmarks

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.
