### ISSUE TITLE
[UI] `True` error message

### ISSUE THREAD

**Issue by Luna-devv** [audn/css-app-frontend#13]
# Issue
Error message just shows `true` instead of the actual error/message.
![image](https://user-images.githubusercontent.com/71079641/210564962-84f90819-5791-484b-b663-cda07401e812.png)

**Edit:**
I am not logged in but that is not obvious, also, there is no way to login (lol)

# Platform
Windows 11; Firefox

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.
