### ISSUE TITLE
components in profile

### ISSUE THREAD

**Issue by Wydady13** [audn/css-app-frontend#15]
**The project that was published in the profile is not counted**
![image 1](https://user-images.githubusercontent.com/107365486/213388787-88ee2084-a849-47b1-80b2-f72983d2d67d.png)
![image 1](https://user-images.githubusercontent.com/107365486/213388881-077dddec-8994-4fe8-b563-8bc024ce3e74.png)

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.
