### ISSUE TITLE
The new component button appears, although it is not registered

### ISSUE THREAD

**Issue by Wydady13** [audn/css-app-frontend#19]
When you go to the site when you are not registered, and when you click on the  button, it must transfer it to the registration page
![ezgif-1-986d2ffeeb 1](https://user-images.githubusercontent.com/107365486/213438606-e9a54343-7146-468b-9ca8-64fe7b0b6738.gif)

**Comment by audn** [comment]
Fixed 🎉 

I will proceed to close the issue.

_Thank you for contributing during beta!_
